<?php
declare(strict_types=1);
function e(?string $v): string { return htmlspecialchars($v ?? '', ENT_QUOTES|ENT_SUBSTITUTE, 'UTF-8'); }
function app_name(): string { return (string)config('app.name','Team Workspace'); }
function base_path(): string { $base=(string)config('app.base_path',''); $base='/'.trim($base,'/'); return $base==='/'?'':$base; }
function url(string $path=''): string { $base=base_path(); $path='/'.ltrim($path,'/'); return $base.($path==='/'?'/':$path); }
function absolute_url(string $path=''): string { return rtrim((string)config('app.url',''),' /').url($path); }
function request_path(): string { $path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH) ?: '/'; $base=base_path(); if($base!=='' && ($path===$base || str_starts_with($path,$base.'/'))) { $path=substr($path,strlen($base)) ?: '/'; } return '/'.ltrim($path,'/'); }
function is_api_request(): bool { return str_starts_with(request_path(),'/api/'); }
function redirect(string $path): never { header('Location: '.url($path)); exit; }
function json_response(array $data, int $status=200): never { http_response_code($status); header('Content-Type: application/json; charset=utf-8'); echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function body_json(): array { $raw=file_get_contents('php://input'); $d=json_decode($raw ?: '{}',true); return is_array($d)?$d:[]; }
function csrf_token(): string { if(empty($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(32)); return $_SESSION['csrf']; }
function verify_csrf(?string $token=null): void { $token=$token ?? ($_POST['_csrf'] ?? ($_SERVER['HTTP_X_CSRF_TOKEN'] ?? null)); if(!$token || !hash_equals($_SESSION['csrf'] ?? '', $token)) json_response(['ok'=>false,'error'=>'CSRF validation failed'],419); }
function current_user(): ?array { if(empty($_SESSION['uid'])) return null; static $u=false; if($u!==false) return $u?:null; $st=db()->prepare('SELECT id,login,role,is_active,created_at,last_login_at FROM users WHERE id=? LIMIT 1'); $st->execute([$_SESSION['uid']]); $u=$st->fetch(); if(!$u || !$u['is_active']) { session_destroy(); return null; } touch_user_activity((int)$u['id']); return $u; }
function require_auth(): array { $u=current_user(); if(!$u) { if(is_api_request()) json_response(['ok'=>false,'error'=>'Unauthorized'],401); redirect('/login'); } return $u; }
function role_rank(string $r): int { return ['user'=>1,'developer'=>2,'founder'=>3][$r] ?? 0; }
function require_role(string ...$roles): array { $u=require_auth(); if(!in_array($u['role'],$roles,true)) { if(is_api_request()) json_response(['ok'=>false,'error'=>'Forbidden'],403); http_response_code(403); render_page('403',['title'=>'Нет доступа']); exit; } return $u; }
function setting(string $key, mixed $default=null): mixed { static $cache=[]; if(array_key_exists($key,$cache)) return $cache[$key]; try { $st=db()->prepare('SELECT value FROM system_settings WHERE `key`=?'); $st->execute([$key]); $r=$st->fetchColumn(); return $cache[$key]=$r===false?$default:$r; } catch(Throwable) { return $default; } }
function set_setting(string $key,string $value,int $uid): void { $st=db()->prepare('INSERT INTO system_settings (`key`,`value`,updated_by) VALUES (?,?,?) ON DUPLICATE KEY UPDATE value=VALUES(value),updated_by=VALUES(updated_by),updated_at=CURRENT_TIMESTAMP'); $st->execute([$key,$value,$uid]); }
function audit(int $listId, ?int $taskId, int $actor, string $action, ?int $from=null, ?int $to=null, ?array $before=null, ?array $after=null, ?array $meta=null): void { $st=db()->prepare('INSERT INTO todo_audit_logs(todo_list_id,task_id,actor_user_id,action,from_category_id,to_category_id,before_data,after_data,metadata) VALUES (?,?,?,?,?,?,?,?,?)'); $st->execute([$listId,$taskId,$actor,$action,$from,$to,$before?json_encode($before,JSON_UNESCAPED_UNICODE):null,$after?json_encode($after,JSON_UNESCAPED_UNICODE):null,$meta?json_encode($meta,JSON_UNESCAPED_UNICODE):null]); }
function event_log(string $type,string $title,int $actor,?int $listId=null,?int $taskId=null,?array $meta=null): void { $st=db()->prepare('INSERT INTO events(type,title,actor_user_id,todo_list_id,task_id,metadata) VALUES (?,?,?,?,?,?)'); $st->execute([$type,$title,$actor,$listId,$taskId,$meta?json_encode($meta,JSON_UNESCAPED_UNICODE):null]); }
function list_access(int $listId, ?array $u, bool $write=false): bool {
    $st=db()->prepare('SELECT visibility,is_archived FROM todo_lists WHERE id=?'); $st->execute([$listId]); $list=$st->fetch(); if(!$list) return false;
    if($u && $u['role']==='founder') return true;
    if((int)$list['is_archived']===1) return false;
    $v=(string)$list['visibility'];
    if(!$u) return !$write && $v==='PUBLIC_READ';
    if($u['role']==='developer') return true;
    if($write) return false;
    if($v==='PUBLIC_READ') return true;
    if($v==='SELECTED_USERS') { $q=db()->prepare('SELECT 1 FROM todo_list_viewers WHERE todo_list_id=? AND user_id=?'); $q->execute([$listId,$u['id']]); return (bool)$q->fetchColumn(); }
    return false;
}
function recent_visible_events(array $u, int $limit=5): array { $limit=max(1,min(50,$limit)); if($u['role']==='founder') return db()->query("SELECT e.*,actor.login FROM events e LEFT JOIN users actor ON actor.id=e.actor_user_id ORDER BY e.id DESC LIMIT $limit")->fetchAll(); if($u['role']==='developer'){ $sql="SELECT e.*,actor.login FROM events e LEFT JOIN users actor ON actor.id=e.actor_user_id LEFT JOIN todo_lists l ON l.id=e.todo_list_id WHERE (e.todo_list_id IS NOT NULL AND l.is_archived=0) OR (e.todo_list_id IS NULL AND (e.actor_user_id=? OR CAST(JSON_UNQUOTE(JSON_EXTRACT(e.metadata,'$.user_id')) AS UNSIGNED)=?)) ORDER BY e.id DESC LIMIT $limit";$st=db()->prepare($sql);$st->execute([(int)$u['id'],(int)$u['id']]);return $st->fetchAll(); } $sql="SELECT DISTINCT e.*,actor.login FROM events e LEFT JOIN users actor ON actor.id=e.actor_user_id LEFT JOIN todo_lists l ON l.id=e.todo_list_id LEFT JOIN todo_list_viewers v ON v.todo_list_id=l.id AND v.user_id=? WHERE (e.todo_list_id IS NULL AND (e.actor_user_id=? OR CAST(JSON_UNQUOTE(JSON_EXTRACT(e.metadata,'$.user_id')) AS UNSIGNED)=?)) OR (e.todo_list_id IS NOT NULL AND l.is_archived=0 AND (l.visibility='PUBLIC_READ' OR (l.visibility='SELECTED_USERS' AND v.user_id IS NOT NULL))) ORDER BY e.id DESC LIMIT $limit";$st=db()->prepare($sql);$st->execute([(int)$u['id'],(int)$u['id'],(int)$u['id']]);return $st->fetchAll(); }
function visibility_label(string $visibility): string { return match($visibility){'TEAM_ONLY'=>'Только команда','SELECTED_USERS'=>'Команда + выбранные пользователи','PUBLIC_READ'=>'Публичный просмотр',default=>$visibility}; }
function page_url(string $path,int $page,array $query=[]):string{$query=array_filter($query,static fn($v)=>$v!==''&&$v!==null);if($page>1)$query['page']=$page;else unset($query['page']);return url($path).($query?'?'.http_build_query($query):'');}
function touch_user_activity(int $userId):void{$now=time();if((int)($_SESSION['activity_touch']??0)>$now-30)return;try{db()->prepare('UPDATE users SET last_seen_at=NOW() WHERE id=?')->execute([$userId]);$_SESSION['activity_touch']=$now;}catch(Throwable){}}
function ensure_runtime_schema():void{static $done=false;if($done)return;$done=true;try{$db=(string)config('database.database','');$st=db()->prepare("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=? AND TABLE_NAME='users' AND COLUMN_NAME='last_seen_at'");$st->execute([$db]);if(!(int)$st->fetchColumn())db()->exec('ALTER TABLE users ADD COLUMN last_seen_at TIMESTAMP NULL DEFAULT NULL AFTER last_login_at');}catch(Throwable){}}
function icon(string $name):string{$p=['home'=>'M3 10.5 12 3l9 7.5V21a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z','tasks'=>'M9 6h11M9 12h11M9 18h11M4 6h.01M4 12h.01M4 18h.01','user'=>'M20 21a8 8 0 0 0-16 0m8-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8','shield'=>'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10','log'=>'M3 3h18v18H3zM7 8h10M7 12h10M7 16h6','plus'=>'M12 5v14M5 12h14','logout'=>'M10 17l5-5-5-5M15 12H3M21 3v18h-8'];$d=$p[$name]??$p['tasks'];return '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="'.e($d).'"/></svg>';}
function render_page(string $view,array $vars=[]):void{extract($vars);$user=current_user();$contentView=__DIR__.'/views/'.$view.'.php';require __DIR__.'/views/layout.php';}
function render_standalone_error(int $code,string $title,string $message):never{$home=url('/');$css=url('/assets/app.css');http_response_code($code);echo '<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.e((string)$code).' · '.e($title).' · '.e(app_name()).'</title><link rel="stylesheet" href="'.e($css).'"></head><body class="error-body"><main class="error-shell"><section class="error-card card"><div class="error-icon">!</div><h1>'.e($title).'</h1><p class="muted">'.e($message).'</p><div class="error-actions"><a class="btn primary" href="'.e($home).'">На главную</a><button class="btn ghost" onclick="history.back()">Назад</button></div></section></main></body></html>';exit;}
